---
language: ruby
cache: bundler
bundler_args: --without development --deployment
rvm:
  - 2.1.1
before_script: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: bundle exec rake test
